// lib/cms/design/presets.ts
// Curated design-system presets, in the spirit of OpenDesign's DESIGN.md
// library (150 brand systems, "switch a system -> the next render uses the new
// tokens"). Each preset is a complete ThemeTokens object that has already been
// authored to pass the Design Guardian. Font stacks are system stacks so no
// external font loading is required.

import type { ThemeTokens } from "./tokens";
import { DEFAULT_THEME } from "./tokens";

export interface ThemePreset {
  id: string;
  name: string;
  description: string;
  tokens: ThemeTokens;
}

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: "clear-professional",
    name: "Clear Professional",
    description: "Restrained, high-trust blue with crisp hierarchy and familiar interaction cues.",
    tokens: {
      bg: "#ffffff",
      surface: "#f3f6fa",
      text: "#172033",
      muted: "#526078",
      accent: "#1456b8",
      accentText: "#ffffff",
      headingFont: "ui-sans-serif, system-ui, 'Segoe UI', Arial, sans-serif",
      bodyFont: "ui-sans-serif, system-ui, 'Segoe UI', Arial, sans-serif",
      radius: "10px",
      shadow: "sm",
      intensity: "tokens",
    },
  },
  {
    id: "neutral-modern",
    name: "Neutral Modern",
    description: "Clean SaaS default. White field, slate text, indigo accent.",
    tokens: { ...DEFAULT_THEME },
  },
  {
    id: "warm-editorial",
    name: "Warm Editorial",
    description: "Cream paper, serif headings, burgundy accent. Magazine feel.",
    tokens: {
      bg: "#faf6ef",
      surface: "#f3ecdf",
      text: "#2b2118",
      muted: "#7a6a58",
      accent: "#8c2f39",
      accentText: "#faf6ef",
      headingFont: "Georgia, 'Times New Roman', serif",
      bodyFont: "Georgia, 'Times New Roman', serif",
      radius: "2px",
      shadow: "none",
      intensity: "overlay",
    },
  },
  {
    id: "dark-neon",
    name: "Dark Neon",
    description: "Near-black field, cyan accent, rounded glow. Late-night product.",
    tokens: {
      bg: "#0a0f1c",
      surface: "#111a2e",
      text: "#e7ecf7",
      muted: "#8b96ad",
      accent: "#22d3ee",
      accentText: "#06121f",
      headingFont: "ui-sans-serif, system-ui, 'Segoe UI', Arial, sans-serif",
      bodyFont: "ui-sans-serif, system-ui, 'Segoe UI', Arial, sans-serif",
      radius: "12px",
      shadow: "lg",
      intensity: "overlay",
    },
  },
  {
    id: "luxury-editorial",
    name: "Luxury Editorial",
    description: "Charcoal and champagne gold. High-end brand voice.",
    tokens: {
      bg: "#141210",
      surface: "#1e1b17",
      text: "#efe9df",
      muted: "#a1988a",
      accent: "#c9a24b",
      accentText: "#141210",
      headingFont: "Georgia, 'Times New Roman', serif",
      bodyFont: "ui-sans-serif, system-ui, 'Segoe UI', Arial, sans-serif",
      radius: "0px",
      shadow: "none",
      intensity: "overlay",
    },
  },
  {
    id: "playful-pop",
    name: "Playful Pop",
    description: "Bright field, punchy coral accent, big radius. Consumer energy.",
    tokens: {
      bg: "#fffdf5",
      surface: "#fff3e0",
      text: "#27221f",
      muted: "#6f6258",
      accent: "#d13d45",
      accentText: "#ffffff",
      headingFont: "'Trebuchet MS', Verdana, sans-serif",
      bodyFont: "Verdana, Geneva, sans-serif",
      radius: "16px",
      shadow: "md",
      intensity: "overlay",
    },
  },
  {
    id: "brutalist-mono",
    name: "Brutalist Mono",
    description: "Paper white, ink black, zero radius, monospace headings.",
    tokens: {
      bg: "#ffffff",
      surface: "#f2f2f2",
      text: "#000000",
      muted: "#555555",
      accent: "#0000ee",
      accentText: "#ffffff",
      headingFont: "'Courier New', Courier, monospace",
      bodyFont: "Arial, Helvetica, sans-serif",
      radius: "0px",
      shadow: "none",
      intensity: "overlay",
    },
  },
  {
    id: "technical-precision",
    name: "Technical Precision",
    description: "Cool neutrals, compact geometry, and a product-forward indigo accent.",
    tokens: {
      bg: "#f8fafc",
      surface: "#eef2f7",
      text: "#111827",
      muted: "#4b5563",
      accent: "#4338ca",
      accentText: "#ffffff",
      headingFont: "ui-sans-serif, system-ui, 'Segoe UI', Arial, sans-serif",
      bodyFont: "ui-sans-serif, system-ui, 'Segoe UI', Arial, sans-serif",
      radius: "6px",
      shadow: "sm",
      intensity: "tokens",
    },
  },
  {
    id: "dark-cinematic",
    name: "Dark Cinematic",
    description: "Deep navy surfaces with a controlled electric-blue accent and spacious hierarchy.",
    tokens: {
      bg: "#0b1220",
      surface: "#121c2d",
      text: "#f4f7fb",
      muted: "#a6b2c5",
      accent: "#66a8ff",
      accentText: "#07101f",
      headingFont: "ui-sans-serif, system-ui, 'Segoe UI', Arial, sans-serif",
      bodyFont: "ui-sans-serif, system-ui, 'Segoe UI', Arial, sans-serif",
      radius: "14px",
      shadow: "lg",
      intensity: "tokens",
    },
  },
  {
    id: "luxury-minimal",
    name: "Luxury Minimal",
    description: "Quiet charcoal and ivory with editorial headings, sparse decoration, and sharp edges.",
    tokens: {
      bg: "#171614",
      surface: "#23211e",
      text: "#f4efe7",
      muted: "#b8aea0",
      accent: "#e1c27a",
      accentText: "#171614",
      headingFont: "Georgia, 'Times New Roman', serif",
      bodyFont: "ui-sans-serif, system-ui, 'Segoe UI', Arial, sans-serif",
      radius: "2px",
      shadow: "none",
      intensity: "tokens",
    },
  },
  {
    id: "friendly-organic",
    name: "Friendly Organic",
    description: "Warm natural surfaces, forest-green actions, and soft approachable shapes.",
    tokens: {
      bg: "#fbf8f1",
      surface: "#f1eadc",
      text: "#243128",
      muted: "#59675c",
      accent: "#1f6b45",
      accentText: "#ffffff",
      headingFont: "Georgia, 'Times New Roman', serif",
      bodyFont: "ui-sans-serif, system-ui, 'Segoe UI', Arial, sans-serif",
      radius: "18px",
      shadow: "sm",
      intensity: "tokens",
    },
  },
  {
    id: "playful-modular",
    name: "Playful Modular",
    description: "Bold violet blocks, generous shapes, and energetic contrast without novelty interactions.",
    tokens: {
      bg: "#fffaf2",
      surface: "#f3e9ff",
      text: "#24152f",
      muted: "#685774",
      accent: "#6d28d9",
      accentText: "#ffffff",
      headingFont: "'Trebuchet MS', Verdana, sans-serif",
      bodyFont: "ui-sans-serif, system-ui, 'Segoe UI', Arial, sans-serif",
      radius: "20px",
      shadow: "md",
      intensity: "tokens",
    },
  },
  {
    id: "high-clarity-utility",
    name: "High-Clarity Utility",
    description: "Maximum legibility, visible boundaries, and minimal decoration for information-heavy sites.",
    tokens: {
      bg: "#ffffff",
      surface: "#f1f3f5",
      text: "#111111",
      muted: "#4a4a4a",
      accent: "#004ea8",
      accentText: "#ffffff",
      headingFont: "Arial, Helvetica, sans-serif",
      bodyFont: "Arial, Helvetica, sans-serif",
      radius: "4px",
      shadow: "none",
      intensity: "tokens",
    },
  },
];

export function getPreset(id: string): ThemePreset | null {
  return THEME_PRESETS.find((p) => p.id === id) || null;
}
